security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #anonymous: lazy
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: catalog
            logout:
                path: app_logout
                target: app_login
            # Required to allow the user to login immediately after registration
            anonymous: true
            lazy: true
            access_denied_url: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

